export const SYNC_CONSTANTS = {
  RETRY_DELAYS_MS: [1000, 2000, 4000] as const,
  MAX_FAILURE_COUNT: 3,
  DEFAULT_DEBOUNCE_MS: 500,
  CONFIG_PERSIST_DELAY_MS: 500,
} as const;

export const ERROR_CODES = {
  NO_CONNECTION: 'CONN_001',
  SYNC_IN_PROGRESS: 'SYNC_001',
  CONFIG_INVALID: 'CFG_001',
  PATH_INVALID: 'PATH_001',
} as const;
